### PR TITLE
Added CLI options

### PR DESCRIPTION
**Pull request by memoryhole**
* Ability to list pattern of files to check
    * Ability to check all files regardless of staged or not!

### CODE REVIEW

**Comment by bung87** [comment]
looks good! do you have idea let user configure pattern from their project's nimble file, like js module husky does. it read config from package.json.

**Comment by memoryhole** [comment]
haha you read my mind, I was thinking of following up with that

**Comment by memoryhole** [comment]
in fact we could just let the user define the tasks there as well, then this would be the equivalent to husky + lint-staged from the node.js ecosystem

**Comment by bung87** [comment]
yeah, that's a cool feature, and that will make this lib's features complete.

**Comment by bung87** [comment]
> in fact we could just let the user define the tasks there as well, then this would be the equivalent to husky + lint-staged from the node.js ecosystem

haha, but pure Nim cooler than it.

**Comment by memoryhole** [comment]
also how do you feel about not installing the githooks by default on install, but letting the user execute ```stage init``` to do so?

**Comment by bung87** [comment]
> also how do you feel about not installing the githooks by default on install, but letting the user execute `stage init` to do so?

install by default is fine to me, I dont want one more steps, as many things to do when I bootstrap a project. `stage init` can make lib more cross platform, as current implementation is shell command in nimble, also can use `inclFilePermissions` as it not suportted in nimscript. further more we can remove or merge existed hooks, current implementation is fine to me.

**Pull request merged**
